descriptions = {
    'Bạch Dương': 'Nghe đây, Bạch Dương! Sao Hỏa đang chiếu mệnh, cho thấy trong con người bạn luôn sục sôi một nguồn năng lượng phi thường. Bạn là người tiên phong, dám nghĩ dám làm, không ngại đương đầu với thử thách. Lòng nhiệt huyết và sự tự tin là ngọn lửa soi đường cho bạn. Tuy nhiên, hãy nhớ kiểm soát sự bốc đồng, đôi khi cái tôi quá lớn có thể gây ra sóng gió trong các mối quan hệ. Hãy học cách lắng nghe và kiên nhẫn hơn, thành công sẽ đến với bạn một cách rực rỡ.',
    'Kim Ngưu': 'Hỡi Kim Ngưu hiền lành! Sao Kim đang bảo hộ bạn, mang đến sự ổn định và giác quan nhạy bén với vẻ đẹp. Bạn là người thực tế, đáng tin cậy, một bờ vai vững chắc cho những người xung quanh. Bạn trân trọng những giá trị vật chất và tìm thấy niềm vui trong những điều bình dị. Sự kiên trì là sức mạnh của bạn, nhưng đừng để sự bảo thủ níu chân bạn khỏi những cơ hội mới. Hãy mở lòng hơn với sự thay đổi, cuộc sống sẽ thêm phần phong phú.',
    'Song Tử': 'Này Song Tử tinh nhanh! Sao Thủy đang ban cho bạn một trí tuệ sắc sảo và khả năng giao tiếp tuyệt vời. Bạn như làn gió thoảng, thích khám phá, học hỏi và kết nối mọi người. Sự linh hoạt giúp bạn dễ dàng thích nghi, nhưng đôi khi sự thiếu tập trung có thể khiến bạn bỏ lỡ những điều quan trọng. Hãy học cách sâu sắc hơn trong suy nghĩ và hành động, sự thông minh của bạn sẽ được phát huy tối đa.',
    'Cự Giải': 'Cự Giải ơi, trái tim ấm áp của bạn đang được Mặt Trăng chiếu rọi! Bạn là người giàu cảm xúc, trắc ẩn và luôn hướng về gia đình. Trực giác của bạn rất mạnh mẽ, hãy tin vào tiếng nói bên trong. Sự nhạy cảm là món quà, nhưng đừng để nó biến bạn thành người quá dễ tổn thương. Hãy học cách bảo vệ trái tim mình và tìm kiếm sự an toàn từ bên trong, hạnh phúc sẽ luôn ở bên bạn.',
    'Sư Tử': 'Sư Tử dũng mãnh! Mặt Trời đang ban cho bạn sự tự tin và khí chất lãnh đạo. Bạn tỏa sáng như vầng dương, thu hút mọi ánh nhìn. Lòng hào phóng và sự nhiệt tình là những phẩm chất đáng quý. Tuy nhiên, đừng để sự kiêu hãnh che mờ đi sự khiêm tốn. Hãy học cách chia sẻ ánh hào quang và quan tâm đến những người xung quanh, bạn sẽ nhận được sự ngưỡng mộ chân thành.',
    'Xử Nữ': 'Xử Nữ tinh tế! Sao Thủy đang soi sáng trí tuệ phân tích của bạn. Bạn là người tỉ mỉ, chú trọng đến từng chi tiết và luôn hướng đến sự hoàn hảo. Tinh thần phục vụ là một phần không thể thiếu trong bạn. Tuy nhiên, đừng quá khắt khe với bản thân và người khác. Hãy học cách chấp nhận sự không hoàn hảo, cuộc sống sẽ trở nên nhẹ nhàng hơn.',
    'Thiên Bình': 'Thiên Bình yêu kiều! Sao Kim đang mang đến sự hài hòa và duyên dáng cho bạn. Bạn luôn tìm kiếm sự cân bằng trong mọi mối quan hệ và có khả năng hòa giải tuyệt vời. Sự lịch thiệp và khả năng giao tiếp giúp bạn được mọi người yêu mến. Tuy nhiên, đôi khi sự do dự có thể khiến bạn bỏ lỡ cơ hội. Hãy tin tưởng vào quyết định của mình và hành động dứt khoát hơn.',
    'Bọ Cạp': 'Bọ Cạp bí ẩn! Sao Hỏa và Diêm Vương đang ban cho bạn một sức mạnh nội tại và trực giác sâu sắc. Bạn là người đam mê, kiên cường và không ngại đối mặt với những thử thách. Khả năng chuyển hóa và tái sinh là một phần đặc biệt của bạn. Tuy nhiên, hãy kiểm soát sự ghen tuông và стремление kiểm soát. Hãy học cách buông bỏ và tin tưởng, bạn sẽ tìm thấy sự bình yên.',
    'Nhân Mã': 'Nhân Mã tự do! Sao Mộc đang mở rộng chân trời tri thức và phiêu lưu cho bạn. Bạn là người lạc quan, yêu thích sự khám phá và luôn tràn đầy năng lượng. Sự thẳng thắn là một đức tính, nhưng đôi khi nó có thể làm tổn thương người khác. Hãy học cách tế nhị hơn trong giao tiếp và kiên nhẫn hơn với những điều chậm rãi.',
    'Ma Kết': 'Ma Kết kiên trì! Sao Thổ đang ban cho bạn sự kỷ luật và trách nhiệm. Bạn là người có mục tiêu rõ ràng và luôn nỗ lực để đạt được thành công. Sự trưởng thành và sự cẩn trọng là những phẩm chất đáng quý. Tuy nhiên, đừng để sự cứng nhắc và quá coi trọng vật chất làm bạn xa cách với những niềm vui giản dị. Hãy học cách thư giãn và tận hưởng cuộc sống.',
    'Bảo Bình': 'Bảo Bình độc đáo! Sao Thổ và Thiên Vương đang khơi dậy sự sáng tạo và tinh thần новатор của bạn. Bạn là người có tư duy tiến bộ, thích những điều mới lạ và luôn quan tâm đến cộng đồng. Sự độc lập là một phần quan trọng của bạn, nhưng đừng để nó biến bạn thành người xa cách. Hãy học cách chia sẻ ý tưởng và kết nối với mọi người một cách chân thành.',
    'Song Ngư': 'Song Ngư mơ mộng! Sao Hải Vương đang ban cho bạn sự nhạy cảm và lòng trắc ẩn vô bờ bến. Bạn là người có tâm hồn nghệ sĩ, dễ đồng cảm và luôn nhìn thế giới bằng đôi mắt lãng mạn. Trí tưởng tượng phong phú là món quà của bạn, nhưng đừng để nó cuốn bạn khỏi thực tại. Hãy học cách cân bằng giữa mơ mộng và thực tế, bạn sẽ tìm thấy sự an yên trong tâm hồn.',
}
